name: voxa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  image_picker: ^0.8.7+3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/bag.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/img/bag.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/bag.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/img/bag.png"

flutter:
  uses-material-design: true

  assets:
    - /home/netorapg/projects/Voxa/voxa/lib/assets/img/bag.png
